### ISSUE TITLE
Is this meant to be public?

### ISSUE THREAD

**Issue by TotallyInformation** [nhsuk/nhs-prototypes-list#7]
https://github.com/nhsuk/nhs-prototypes-list

Had this reported to me by someone on a random forum.

**Comment by chrimesdev** [comment]
Hi @TotallyInformation 

The reason we password protect prototypes when they are published to the web is to prevent general members of the public randomly coming across them and thinking they are real services. They aren’t password protected for security purposes. We often put our prototypes code (and sometimes production code) in public repositories on GitHub, so if you know where to look, you won’t even need the password anyway.
 
The purpose of the public prototype list repository is so that the wider NHS designer community can share prototypes with each other. Every prototype on that list has been added by choice (the repo is community owned), so they are happy with the access being open and for people to see them.
 
That being said we should always be careful of using any sensitive or personal data when designing services to begin with.

**Comment by TotallyInformation** [comment]
Thanks for responding. You might want to put something on the page to prevent others from misinterpreting things. 

Can you please get the owner of the NHSuk GitHub to reach out to me though so that we both know who we can contact in the future and work more effectively together? It would be worth having a contact form or email address on the org page so that people can get in touch if needed.

![image](https://user-images.githubusercontent.com/1591850/121081738-0ae9fb80-c7d5-11eb-938b-20974098bd68.png)
![image](https://user-images.githubusercontent.com/1591850/121081884-353bb900-c7d5-11eb-9949-f23d6f21578d.png)


They can find my address on NHSmail under NHS England if they don't already have it.

Thanks.
